(defun formatter---format-buffer (buf cmd)
  (when-let* ((buf (or buf (current-buffer)))
	      (current-line (buffer-current-line-number))
	      (fname (buffer-file-name buf))
	      (buf-size (length (buffer2string buf nil nil)))
	      (cmd (if (string-match "%s" cmd)
		       (string-replace "%s" fname cmd)
		     (format "%s %s" cmd fname)))
	      (output (shell-command-to-string cmd))
	      (output-size (length output))
	      (invalid-output? (< (/ buf-size 2) output-size)))
    (with-current-buffer buf		
      (save-buffer)
      (buffer-set-string buf output)
      (goto-line current-line)
      (end-of-line)
      t)))

(defun formatter-format-buffer (&optional buf)
  (interactive)
  (if-let* ((buf (or buf (current-buffer)))
	    (ft (buffer-lang buf))
	    (cmd (lang-buffer-command buf ft 'formatter)))
      (formatter---format-buffer buf cmd)
    (message "no formatter defined for %s" (buffer-major-mode (or buf (current-buffer))))))

(defalias 'format-buffer 'formatter-format-buffer)
